import type { CategoryInfo, EditorialPick, Phone } from './types'

/**
 * Realistic fallback catalog used until the live API is connected.
 * Prices are indicative DZD values for the Algerian market.
 */
export const FALLBACK_PHONES: Phone[] = [
  {
    id: 1,
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    price: 289000,
    score: 9.4,
    category: 'Flagship',
    highlight: 'كاميرا 200 ميجابكسل وأداء استثنائي مع قلم S Pen',
    specs: {
      display: '6.8" QHD+ AMOLED 120Hz',
      chipset: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB',
      battery: '5000mAh',
      mainCamera: '200MP + 50MP + 12MP + 10MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 2,
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    price: 312000,
    score: 9.5,
    category: 'Flagship',
    highlight: 'شريحة A17 Pro وهيكل تيتانيوم فائق الخفة',
    specs: {
      display: '6.7" Super Retina XDR 120Hz',
      chipset: 'Apple A17 Pro',
      ram: '8GB',
      storage: '256GB',
      battery: '4441mAh',
      mainCamera: '48MP + 12MP + 12MP',
      os: 'iOS 17',
      releaseYear: 2023,
    },
  },
  {
    id: 3,
    brand: 'Google',
    model: 'Pixel 8 Pro',
    price: 215000,
    score: 9.1,
    category: 'Flagship',
    highlight: 'أفضل معالجة صور بالذكاء الاصطناعي من Google',
    specs: {
      display: '6.7" LTPO OLED 120Hz',
      chipset: 'Google Tensor G3',
      ram: '12GB',
      storage: '128GB',
      battery: '5050mAh',
      mainCamera: '50MP + 48MP + 48MP',
      os: 'Android 14',
      releaseYear: 2023,
    },
  },
  {
    id: 4,
    brand: 'Xiaomi',
    model: '14 Ultra',
    price: 245000,
    score: 9.2,
    category: 'Flagship',
    highlight: 'كاميرا Leica رباعية بفتحة عدسة متغيرة',
    specs: {
      display: '6.73" LTPO AMOLED 120Hz',
      chipset: 'Snapdragon 8 Gen 3',
      ram: '16GB',
      storage: '512GB',
      battery: '5300mAh',
      mainCamera: '50MP Leica Quad',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 5,
    brand: 'Samsung',
    model: 'Galaxy S24+',
    price: 198000,
    score: 8.9,
    category: 'Upper Mid-Range',
    highlight: 'شاشة كبيرة وبطارية تدوم طوال اليوم',
    specs: {
      display: '6.7" QHD+ AMOLED 120Hz',
      chipset: 'Exynos 2400',
      ram: '12GB',
      storage: '256GB',
      battery: '4900mAh',
      mainCamera: '50MP + 12MP + 10MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 6,
    brand: 'OnePlus',
    model: '12',
    price: 172000,
    score: 8.8,
    category: 'Upper Mid-Range',
    highlight: 'شحن فائق السرعة 100W وأداء سلس',
    specs: {
      display: '6.82" LTPO AMOLED 120Hz',
      chipset: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB',
      battery: '5400mAh',
      mainCamera: '50MP + 64MP + 48MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 7,
    brand: 'Google',
    model: 'Pixel 8',
    price: 148000,
    score: 8.7,
    category: 'Upper Mid-Range',
    highlight: 'تجربة Android نقية مع تحديثات لسبع سنوات',
    specs: {
      display: '6.2" OLED 120Hz',
      chipset: 'Google Tensor G3',
      ram: '8GB',
      storage: '128GB',
      battery: '4575mAh',
      mainCamera: '50MP + 12MP',
      os: 'Android 14',
      releaseYear: 2023,
    },
  },
  {
    id: 8,
    brand: 'Xiaomi',
    model: '14',
    price: 156000,
    score: 8.8,
    category: 'Upper Mid-Range',
    highlight: 'حجم مثالي مع كاميرا Leica احترافية',
    specs: {
      display: '6.36" LTPO OLED 120Hz',
      chipset: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB',
      battery: '4610mAh',
      mainCamera: '50MP Leica Triple',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 9,
    brand: 'Nothing',
    model: 'Phone (2)',
    price: 132000,
    score: 8.4,
    category: 'Upper Mid-Range',
    highlight: 'تصميم شفاف مميز مع واجهة Glyph',
    specs: {
      display: '6.7" LTPO OLED 120Hz',
      chipset: 'Snapdragon 8+ Gen 1',
      ram: '12GB',
      storage: '256GB',
      battery: '4700mAh',
      mainCamera: '50MP + 50MP',
      os: 'Android 13',
      releaseYear: 2023,
    },
  },
  {
    id: 10,
    brand: 'Samsung',
    model: 'Galaxy A55',
    price: 78000,
    score: 8.1,
    category: 'Mid-Range',
    highlight: 'هيكل معدني وشاشة Super AMOLED رائعة',
    specs: {
      display: '6.6" Super AMOLED 120Hz',
      chipset: 'Exynos 1480',
      ram: '8GB',
      storage: '128GB',
      battery: '5000mAh',
      mainCamera: '50MP + 12MP + 5MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 11,
    brand: 'Xiaomi',
    model: 'Redmi Note 13 Pro+',
    price: 68000,
    score: 8.2,
    category: 'Mid-Range',
    highlight: 'كاميرا 200 ميجابكسل بسعر تنافسي',
    specs: {
      display: '6.67" AMOLED 120Hz',
      chipset: 'Dimensity 7200 Ultra',
      ram: '8GB',
      storage: '256GB',
      battery: '5000mAh',
      mainCamera: '200MP + 8MP + 2MP',
      os: 'Android 13',
      releaseYear: 2024,
    },
  },
  {
    id: 12,
    brand: 'Motorola',
    model: 'Edge 50 Pro',
    price: 82000,
    score: 8.0,
    category: 'Mid-Range',
    highlight: 'شاشة منحنية أنيقة وشحن سريع 125W',
    specs: {
      display: '6.7" pOLED 144Hz',
      chipset: 'Snapdragon 7 Gen 3',
      ram: '12GB',
      storage: '256GB',
      battery: '4500mAh',
      mainCamera: '50MP + 13MP + 10MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 13,
    brand: 'Realme',
    model: '12 Pro+',
    price: 74000,
    score: 8.0,
    category: 'Mid-Range',
    highlight: 'عدسة تقريب بيريسكوب نادرة في هذه الفئة',
    specs: {
      display: '6.7" Curved AMOLED 120Hz',
      chipset: 'Snapdragon 7s Gen 2',
      ram: '12GB',
      storage: '256GB',
      battery: '5000mAh',
      mainCamera: '50MP + 64MP + 8MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 14,
    brand: 'OnePlus',
    model: 'Nord 3',
    price: 71000,
    score: 7.9,
    category: 'Mid-Range',
    highlight: 'أداء قوي وشاشة سلسة للألعاب',
    specs: {
      display: '6.74" AMOLED 120Hz',
      chipset: 'Dimensity 9000',
      ram: '8GB',
      storage: '128GB',
      battery: '5000mAh',
      mainCamera: '50MP + 8MP + 2MP',
      os: 'Android 13',
      releaseYear: 2023,
    },
  },
  {
    id: 15,
    brand: 'Samsung',
    model: 'Galaxy A25',
    price: 46000,
    score: 7.5,
    category: 'Budget',
    highlight: 'شاشة AMOLED وبطارية كبيرة بسعر مناسب',
    specs: {
      display: '6.5" Super AMOLED 120Hz',
      chipset: 'Exynos 1280',
      ram: '6GB',
      storage: '128GB',
      battery: '5000mAh',
      mainCamera: '50MP + 8MP + 2MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 16,
    brand: 'Xiaomi',
    model: 'Redmi Note 13',
    price: 38000,
    score: 7.6,
    category: 'Budget',
    highlight: 'قيمة ممتازة مقابل السعر لكل يوم',
    specs: {
      display: '6.67" AMOLED 120Hz',
      chipset: 'Snapdragon 685',
      ram: '6GB',
      storage: '128GB',
      battery: '5000mAh',
      mainCamera: '108MP + 8MP + 2MP',
      os: 'Android 13',
      releaseYear: 2024,
    },
  },
  {
    id: 17,
    brand: 'Realme',
    model: 'C67',
    price: 32000,
    score: 7.2,
    category: 'Budget',
    highlight: 'تصميم عصري وبطارية تدوم طويلاً',
    specs: {
      display: '6.72" IPS LCD 90Hz',
      chipset: 'Snapdragon 685',
      ram: '8GB',
      storage: '128GB',
      battery: '5000mAh',
      mainCamera: '108MP + 2MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 18,
    brand: 'Infinix',
    model: 'Note 40 Pro',
    price: 41000,
    score: 7.4,
    category: 'Budget',
    highlight: 'شحن لاسلكي نادر في هذه الفئة السعرية',
    specs: {
      display: '6.78" AMOLED 120Hz',
      chipset: 'Helio G99 Ultimate',
      ram: '8GB',
      storage: '256GB',
      battery: '5000mAh',
      mainCamera: '108MP + 2MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 19,
    brand: 'Tecno',
    model: 'Camon 30 Pro',
    price: 44000,
    score: 7.3,
    category: 'Budget',
    highlight: 'كاميرا سيلفي عالية الدقة للمحتوى',
    specs: {
      display: '6.78" AMOLED 120Hz',
      chipset: 'Dimensity 8200 Ultra',
      ram: '8GB',
      storage: '256GB',
      battery: '5000mAh',
      mainCamera: '50MP + 50MP + 2MP',
      os: 'Android 14',
      releaseYear: 2024,
    },
  },
  {
    id: 20,
    brand: 'Apple',
    model: 'iPhone 15',
    price: 224000,
    score: 9.0,
    category: 'Flagship',
    highlight: 'منفذ USB-C وكاميرا 48 ميجابكسل محسّنة',
    specs: {
      display: '6.1" Super Retina XDR 60Hz',
      chipset: 'Apple A16 Bionic',
      ram: '6GB',
      storage: '128GB',
      battery: '3349mAh',
      mainCamera: '48MP + 12MP',
      os: 'iOS 17',
      releaseYear: 2023,
    },
  },
]

export const CATEGORIES: CategoryInfo[] = [
  {
    key: 'Flagship',
    label: 'الفئة الرائدة',
    description: 'أقوى الهواتف بأحدث التقنيات',
  },
  {
    key: 'Upper Mid-Range',
    label: 'الفئة المتوسطة العليا',
    description: 'أداء ممتاز بسعر أذكى',
  },
  {
    key: 'Mid-Range',
    label: 'الفئة المتوسطة',
    description: 'توازن مثالي بين السعر والمواصفات',
  },
  {
    key: 'Budget',
    label: 'الفئة الاقتصادية',
    description: 'أفضل قيمة مقابل كل دينار',
  },
]

export const EDITORIAL_PICKS: EditorialPick[] = [
  {
    id: 'best-camera',
    phoneId: 2,
    tag: 'أفضل كاميرا',
    title: 'iPhone 15 Pro Max',
    reason:
      'اختيار عبدو لعشّاق التصوير: نظام كاميرات ثابت في كل الظروف مع تصوير سينمائي احترافي وأداء لا يتردد.',
  },
  {
    id: 'best-value',
    phoneId: 11,
    tag: 'أفضل قيمة',
    title: 'Redmi Note 13 Pro+',
    reason:
      'مواصفات الفئة العليا بسعر الفئة المتوسطة: كاميرا 200 ميجابكسل وشاشة AMOLED وشحن سريع دون إرهاق ميزانيتك.',
  },
  {
    id: 'best-battery',
    phoneId: 6,
    tag: 'أفضل بطارية وأداء',
    title: 'OnePlus 12',
    reason:
      'للمستخدم الذي لا يتوقف: بطارية ضخمة، شحن 100W يملأها في دقائق، ومعالج رائد يلتهم أي مهمة.',
  },
]
